version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: scaffold-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: scaffold_db
      MYSQL_USER: scaffold
      MYSQL_PASSWORD: scaffold123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/db_init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - scaffold-network
    restart: unless-stopped

  # Spring Boot Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scaffold-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/scaffold_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - scaffold-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis (Optional)
  redis:
    image: redis:7-alpine
    container_name: scaffold-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - scaffold-network
    restart: unless-stopped
    command: redis-server --requirepass redis123

volumes:
  mysql_data:
  redis_data:

networks:
  scaffold-network:
    driver: bridge